services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "7860:7860"
    volumes:
      - ./conversation_logs:/app/conversation_logs
